artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://wri-dataportal-prod.s3.amazonaws.com/manual/global_power_plant_database_v_1_3.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/global_power_plant_database.csv
  status_file: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/global_power_plant_database.csv
  clean_data_dir: artifacts/data_transformation/clean_data
  serialized_objects_dir: artifacts/serialized_objects
  data_pivot_name: data_pivot.pkl
  data_names_name: data_names.pkl

model_trainer:
  serialized_objects_dir: artifacts/serialized_objects
  root_dir: artifacts/model_trainer
  trained_model_name: model.pkl
  data_pivot_name: data_pivot.pkl
  data_names_name: data_names.pkl